name: Dev Check-in Tests (API)

on:
  push:
    branches:
      - 'fastAPI*'
  pull_request:
    branches:
      - 'fastAPI*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: fastAPI
        run: |
          python -m venv venv
          ./venv/bin/python -m pip install --upgrade pip
          ./venv/bin/python -m pip install -r requirements.txt
      - name: Run API tests
        working-directory: fastAPI
        run: |
          ./venv/bin/python -m pytest tests/ --disable-warnings --maxfail=5