name: Test GCE SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa_test
          chmod 600 ~/.ssh/id_rsa_test

          ssh-keyscan -t rsa,ecdsa,ed25519 ${{ secrets.SERVER_HOST }} | tee ~/.ssh/known_hosts

          echo "✅ known_hosts populated (Test):"
          cat ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -tt -i ~/.ssh/id_rsa_test -o StrictHostKeyChecking=yes ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "bash -c 'echo ✅ GitHub Actions SSH to TEST is working!'"
